spring:
  application:
    name: mybatis-plus-demo
  datasource:
    username: root
    password: Yhd_19941108
    url: jdbc:mysql://localhost:3306/sakila

logging:
  level:
    com.bridsnail.demo.mybatisplus.mapper: debug