spring:
  application:
    name: nacos-config-demo
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml
        group: dev
        username: nacos
        password: nacos
        namespace: ${nacos.namespace}
  profiles:
    #    激活test组配置的全部环境
    active: test
    #    active: prod
#    group:
#      test: prod,group1,group2

test:
  dog:
    color: 黄色
    name: 本地配置小狗
  user:
    name: yang
    age: 23

# dev环境配置
---
spring:
  config:
    activate:
      on-profile: dev
    import:
      # 拉取nacos配置：傳入dataId
      - nacos:cat?group=animal
      - classpath:dog.yaml
      - optional:classpath:cat.yaml
nacos:
  namespace: 99fbc78b-650f-4fb2-adf9-1d85c18f38ed

# test 环境配置
---
spring:
  config:
    activate:
      on-profile: test
    import:
      # 拉取nacos配置：傳入dataId
      - nacos:cat?group=animal
      - nacos:dog?group=animal
nacos:
  namespace: 3b85f0e2-f551-4a87-bf65-c1c3c652be9e

# prod环境配置
---
spring:
  config:
    import:
      # 拉取nacos配置：傳入dataId
      - nacos:person?group=prod
    activate:
      on-profile: prod

# group1
---
spring:
  config:
    activate:
      on-profile: group1
test:
  group1:
    name: group1
    desc: spring config group使用demo，本组为group1

# group2
---
spring:
  config:
    activate:
      on-profile: group2
test:
  group2:
    name: group2
    desc: spring config group使用demo，本组为group2